# Generated by Django 5.2 on 2025-04-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_tguser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='inactive_notified',
            field=models.BooleanField(default=False),
        ),
    ]
