# Generated by Django 5.2 on 2025-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_tguser_inactive_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_changer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_sheff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requsage',
            name='photo',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
