# Generated by Django 5.2 on 2025-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_invoice_sent_changer_invoice_sent_sheff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
