# Generated by Django 5.2 on 2025-04-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_req_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalmode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='withdrawalmode',
            name='invoices',
            field=models.ManyToManyField(to='tg.invoice'),
        ),
        migrations.AlterField(
            model_name='req',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
