# Generated by Django 5.2 on 2025-04-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_withdrawalmode_active_withdrawalmode_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalmode',
            name='ltc_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalmode',
            name='requisite',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
