# Generated by Django 5.2 on 2025-04-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_withdrawalmode_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='referral_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
