# Generated by Django 5.2 on 2025-04-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_invoice_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('amount_in_usdt', models.FloatField()),
                ('one_time_req', models.BooleanField(blank=True, default=False, null=True)),
                ('invoices_for_zp_cart', models.ManyToManyField(to='tg.invoice')),
            ],
        ),
    ]
