# Generated by Django 5.2 on 2025-04-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_anotherreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_ref',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
