# Generated by Django 5.2 on 2025-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0012_invoice_sent_ref_alter_tguser_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
