# Generated by Django 5.2 on 2025-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0013_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalmode',
            name='ref_invoices',
            field=models.ManyToManyField(related_name='ref_invoices', to='tg.invoice'),
        ),
        migrations.AlterField(
            model_name='withdrawalmode',
            name='invoices',
            field=models.ManyToManyField(related_name='invoices', to='tg.invoice'),
        ),
    ]
