# Generated by Django 5.2 on 2025-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0014_withdrawalmode_ref_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='prc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
