# Generated by Django 5.2 on 2025-04-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0015_shop_prc'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='prc',
            field=models.FloatField(blank=True, default=13.5, null=True),
        ),
    ]
