# Generated by Django 5.2 on 2025-04-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0016_promo_shop_alter_shop_prc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_admin',
            field=models.BooleanField(default=False),
        ),
    ]
